---
- name: Update Ubuntu packages
  hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Install nginx
      apt:
        name: nginx
        state: present
