---
- name: Wait for connection to be available
  hosts: all
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: trainee-bkt
    ansible_aws_ssm_region: eu-central-1
    # When the S3 bucket isn't in the same region as the Instance
    # Explicitly setting the addressing style to 'virtual' may be necessary
    # https://repost.aws/knowledge-center/s3-http-307-response
    # ansible_aws_ssm_s3_addressing_style: virtual
  tasks:
    - name: Wait for connection
      wait_for_connection:

- name: Install a Nginx Package
  hosts: all
  become: true
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: trainee-bkt
    ansible_aws_ssm_region: eu-central-1
  tasks:
    - name: Install a Nginx Package
      dnf:
        name: nginx
        state: present
    - name: Start and enable nginx service
      service:
        name: nginx
        state: started
        enabled: yes
